apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend-deployment
  namespace: remember-this
  labels:
    app: remember-this
    tier: backend
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: remember-this
      tier: backend
  template:
    metadata:
      name: spring-boot
      namespace: remember-this
      labels:
        app: remember-this
        tier: backend
    spec: 
      containers: 
        - name: backend-pod
          image: willey599/backend:6ba7ab2dd2180dbc5d9b6f01e152e2f5ed624c29
          ports: 
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              value: "mysql"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: mysql-database-name
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: secrets
                  key: mysql-password
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef: 
                  name: secrets
                  key: google-client-id
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: google-client-secret
          resources: 
            requests:
              cpu: "300m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"